name: Deploy to Pages

on:
  push:
    branches:
      - master

jobs:
  github-pages-deploy:
    runs-on: ubuntu-latest
    concurrency: ci-${{github.ref}} # Recommended if you intend to make multiple deployments in quick succession.
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn
      - run: yarn build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build # The folder the action should deploy.
          token: ${{ secrets.TOKEN_REPO }}